-- ===========================================================================
-- Analysis : magnitude analysis
-- Purpose : quantifies data distribution across warehouse dimensions.
-- Run : psql -d datawarehouse -f sql/analytics/analysis/magnitude_analysis.sql
-- ===========================================================================

-- ===========================================================================
-- Total customers by country.
-- ===========================================================================
SELECT
    dim_customers.country,
    COUNT(dim_customers.customer_key) AS total_customers
FROM warehouse.dim_customers AS dim_customers

GROUP BY
    dim_customers.country

ORDER BY
    total_customers DESC;

-- ===========================================================================
-- Total customers by gender.
-- ===========================================================================
SELECT
    dim_customers.gender,
    COUNT(dim_customers.customer_key) AS total_customers
FROM warehouse.dim_customers AS dim_customers

GROUP BY
    dim_customers.gender

ORDER BY
    total_customers DESC;

-- ===========================================================================
-- Total products by category.
-- ===========================================================================
SELECT
    dim_products.category,
    COUNT(dim_products.product_sk) AS total_products
FROM warehouse.dim_products AS dim_products

GROUP BY
    dim_products.category

ORDER BY
    total_products DESC;

-- ===========================================================================
-- Average cost in each category.
-- ===========================================================================
SELECT
    dim_products.category,
    AVG(dim_products.cost) AS avg_cost
FROM warehouse.dim_products AS dim_products

GROUP BY
    dim_products.category

ORDER BY
    avg_cost DESC;

-- ===========================================================================
-- Total revenue generated for each category.
-- ===========================================================================
SELECT
    dim_products.category,
    SUM(fact_sales.sales_amount) AS total_revenue
FROM warehouse.fact_sales AS fact_sales
LEFT JOIN warehouse.dim_products AS dim_products
    ON fact_sales.product_key = dim_products.product_sk

GROUP BY
    dim_products.category

ORDER BY
    total_revenue DESC;

-- ===========================================================================
-- Total revenue generated by each customer.
-- ===========================================================================
SELECT
    dim_customers.customer_key,
    dim_customers.first_name,
    dim_customers.last_name,
    SUM(fact_sales.sales_amount) AS total_revenue
FROM warehouse.fact_sales AS fact_sales
LEFT JOIN warehouse.dim_customers AS dim_customers
    ON fact_sales.customer_key = dim_customers.customer_sk

GROUP BY
    dim_customers.customer_key,
    dim_customers.first_name,
    dim_customers.last_name

ORDER BY
    total_revenue DESC;

-- ===========================================================================
-- Distribution of sold items across countries.
-- ===========================================================================
SELECT
    dim_customers.country,
    SUM(fact_sales.quantity) AS total_sold_items
FROM warehouse.fact_sales AS fact_sales
LEFT JOIN warehouse.dim_customers AS dim_customers
    ON fact_sales.customer_key = dim_customers.customer_sk

GROUP BY
    dim_customers.country

ORDER BY
    total_sold_items DESC;
